- alias: hasura
  config:
    configmap: controller-conf
    namespace: barge80-hasura
  data: null
  kubeContext: barge80
  name: barge80
- alias: production
  config:
    configmap: controller-conf
    namespace: bearishness40-hasura
  data: null
  kubeContext: bearishness40
  name: bearishness40
